### ISSUE TITLE
Header/Footer

### ISSUE THREAD

**Issue by rcammack** [wash-n-dash/wash-n-dash#1]
Do all work for this task in a branch called issue-1

edit top navbar
once logged in the login should change to reflect the signed-in user's username

Edit the footer component so it contains relevant information pertaining to the app.

**Comment by rcammack** [comment]
When you complete an issue:
1. move issue to "done" column
2. Mark the issue as closed
3. Merge the associated branch into Master

**Comment by prattheev** [comment]
@rcammack I would like to contribute for this. :smiley:
