### ISSUE TITLE
report page -if no reports exist

### ISSUE THREAD

**Issue by rcammack** [wash-n-dash/wash-n-dash#21]
do all work for this issue in branch issue-21

for the table on the report page, if there are no reports, add some row or something saying so (cuz right now if there are no reports, it looks weird) 

<img width="812" alt="screen shot 2018-05-02 at 10 54 28 am" src="https://user-images.githubusercontent.com/25333825/39548740-3a0d3748-4df7-11e8-94f8-ee9e84e6df70.png">

**Comment by jpham79** [comment]
Closing because not necessary. This is only on admin side.
