### ISSUE TITLE
add filtering system to machine page

### ISSUE THREAD

**Issue by rcammack** [wash-n-dash/wash-n-dash#29]
do all work for this issue in branch issue-29

remove washer/dryer headers and current filtering system
add 2 dropdowns to the top of the 'check availability' page with the following options:  
1. washers, dryers
2. each laundry room (find all unique 'location' fields in the machine database)

**Comment by rcammack** [comment]
possibly use search - https://react.semantic-ui.com/modules/search

**Comment by rcammack** [comment]
https://react.semantic-ui.com/modules/dropdown#dropdown-example-multiple-search-selection

**Comment by rcammack** [comment]
i made the dropdowns but I'm not 100% sure how to use it to filter anything

**Comment by davidrb** [comment]
I just added the filtering. Should be done.
