### ISSUE TITLE
Reformat Cards

### ISSUE THREAD

**Issue by Olivia-Murray** [wash-n-dash/wash-n-dash#33]
do all work for this issue in branch issue-33

Available washer/dryer card -> green icon on card
Not available washer/dryer card -> red/black? icon on card
Disabled washer/dryer card grayed out/disabled buttons

washer/dryers with any existing reports should have a warning icon next to name

**Comment by rcammack** [comment]
i added a warning icon and tried to make it only appear when reports for that machine exist, but it's not working currently.  I pushed the changes for you to see though @Olivia-Murray

**Comment by rcammack** [comment]
ok so i made it so if time remaining is 0, then the icon will be green, otherwise it's black
