### ISSUE TITLE
Washing Machine Mongo DB

### ISSUE THREAD

**Issue by davidrb** [wash-n-dash/wash-n-dash#9]
Do all work for this issue in a branch called issue-9.

create collection for washing machine usage status'

**Comment by jpham79** [comment]
Perhaps the MachineSchema could also use a machineId field, so we can keep track of which ones are which.

**Comment by davidrb** [comment]
There is a machineType field that is either 'washer' or 'dryer.' Is that what you mean? @jpham79

**Comment by jpham79** [comment]
I was thinking like 1, 2, 3 , 4 etc to distinguish between machines or perhaps we don't need it?
@davidrb

**Comment by davidrb** [comment]
I think we can use the mongodb id's for that. Could be wrong though.
@jpham79
